### PR TITLE
Bump az-tdx-vtpm & az-snp-vtpm from 0.6 to 0.7.0

### PR DESCRIPTION
**Pull request by pawelpros**
- Bump az-tdx-vtpm from 0.6.0 to 0.7.0
- Bump az-snp-vtpm from 0.6.0 to 0.7.0
- Bump base64 from 0.22.0 to 0.22.1

### CODE REVIEW

**Comment by pawelpros** [comment]
This PR is prior next one: https://github.com/confidential-containers/guest-components/pull/710

**Review by mkulke — APPROVED** [review]

**Review by fitzthum — APPROVED** [review]
LGTM.

Do we need to do this on the Trustee side as well?

**Comment by pawelpros** [comment]
@fitzthum yes - separare PR is also created for trustee:
https://github.com/confidential-containers/trustee/pull/493/files

**Comment by mythi** [comment]
@pawelpros can you rebase this PR so get CI re-triggered.

**Comment by pawelpros** [comment]
Sure, already pushed rebase

**Comment by mythi** [comment]
the remaining error looks like a network glitch?

**Pull request merged**
