### PR TITLE
AA & CDH | Add feature information and git sha via `-V`

### LINKED ISSUE #530: CDH & AA | Add option to show built-in plugins

### PR DESCRIPTION
**Pull request by Xynnn007**
Fixes #530 

After this PR, the AA would show its built-in plugins by `-V` like the following
```
$ ./attestation-agent -V

attestation-agent 

Commit Hash: 083cb8750c325c7d90147f3bce1f498664e376fb (dirty)
Supported Attesters: TDX_ATTESTER, SGX_ATTESTER, AZ_SNP_VTPM_ATTESTER, AZ_TDX_VTPM_ATTESTER, SNP_ATTESTER
Token plugins: KBS, COCO_AS
```

and CDH
```
$ ./confidential-data-hub -V

confidential-data-hub 

Commit Hash: 083cb8750c325c7d90147f3bce1f498664e376fb (dirty)
Resource Providers: KBS, SEV
KMS plugins: ALIYUN, EHSM
```

Related to also #487 

cc @fitzthum @surajssd @mkulke

### CODE REVIEW

**Review by mkulke — COMMENTED** [review]
there's this:

image

maybe we can use it for the attester features?

**Comment by fitzthum** [comment]
> maybe we can use it for the attester features?

We are using that. The list is just all the different features to check for.

**Comment by Xynnn007** [comment]
> LGTM.
> 
> Slightly annoying that we'll need to update the feature lists here, but this seems like a pretty standard way of doing things.

yes. We need to break the all-attesters features into small features or the information would be only one All-attester rather than separate different attesters.

**Comment by Xynnn007** [comment]
Ok @mkulke Please feel free to merge this if it looks good to you, or share any suggestions.

**Review by mkulke — APPROVED** [review]
thanks, this will be very helpful for debugging! lgtm

**Pull request merged**
