### PR TITLE
attester: tdx: Improve extend runtime measurement handling

### PR DESCRIPTION
**Pull request by jodh-intel**
Some systems do not yet provide the ability to extend runtime measurement so add a check to allow a more meaningful error to be returned.

### CODE REVIEW

**Comment by Xynnn007** [comment]
cc @jialez0

**Review by mythi — APPROVED** [review]
LGTM. I had chatted about this with @jodh-intel offline. 

`detect_platform()` cannot cover all the different variations between "in-tree" and "out-of-tree" TDX support so this is the simplest approach to let the user know what is expected to work.

**Comment by Xynnn007** [comment]
Let's merge https://github.com/confidential-containers/guest-components/pull/467 before this PR, because potential conflict might not be resolved as @Lu-Biao would not be here for some time.

**Review by Xynnn007 — APPROVED** [review]
lgtm

**Pull request merged**
