### PR TITLE
Update `az-snp-vtpm` version to avoid vendor openssl

### LINKED ISSUE #346: `cargo test` cannot pass due to csv-rs doesn't support openssl version:806354976
the issue can be found from here:
https://github.com/confidential-containers/guest-components/actions/runs/6105168876/job/16568311628?pr=321

```
Error: failed to run custom build command for `csv-rs v0.1.0 (https://gitee.com/anolis/csv-rs?rev=bcf3bcc#bcf3bcc0)`
Caused by:
  process didn't exit successfully: `/home/runner/work/guest-components/guest-components/target/debug/build/csv-rs-c4227a814abf3087/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unsupported openssl version:806354976', /home/runner/.cargo/git/checkouts/csv-rs-6ce26198efa2f606/bcf3bcc/build.rs:19:18
```

and can be verified locally, 
```
cargo test --features openssl,rust-crypto,offline_fs_kbc -p attestation-agent -p attester -p coco_keyprovider -p kbc -p kbs_protocol -p attestation_agent -p crypto -p resource_uri -p sev@0.1.0
```

Tried to revert the change here: https://github.com/confidential-containers/guest-components/pull/342, but still doesn't work.

```
  = note: /usr/bin/ld: /go/src/github.com/confidential-containers/guest-components/target/debug/deps/libcsv_rs-cf8059eec6404d4e.rlib(csv_rs-cf8059eec6404d4e.csv_rs.fbdd6b72ef39f42a-cgu.11.rcgu.o): undefined reference to symbol 'EVP_PKEY_set_alias_type@@OPENSSL_1_1_1'
          /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by jialez0**
Fix #346

### CODE REVIEW

**Comment by chendave** [comment]
@jialez0 I tried this, still cannot pass, but let's see, maybe it's clear env in my side.

**Comment by jialez0** [comment]
@BaoshunFang Could you please help to take a look at the CI error here?

**Comment by Xynnn007** [comment]
probably related to https://gitee.com/anolis/csv-rs/blob/master/build.rs#L19 cc @BaoshunFang

**Comment by chendave** [comment]
who set this `DEP_OPENSSL_VERSION_NUMBER`?  I searched in the both `rust-openssl` and `openssl`,  `806354976` doesn't seem like a valid commit ID.

**Comment by BaoshunFang** [comment]
who set this DEP_OPENSSL_VERSION_NUMBER? I searched in the both rust-openssl and openssl, 806354976 doesn't seem like a valid commit ID.
---
@chendave  convert to hexadecimal: 0x 30100020, if no vendored set to openssl, it's the version of the openssl installed in the system.

**Pull request closed without merging**
