### PR TITLE
AA: use URL safe base64 encoding for TeePubKey

### PR DESCRIPTION
**Pull request by katexochen**
Port of https://github.com/confidential-containers/attestation-agent/pull/211

---

Fixes https://github.com/confidential-containers/guest-components/issues/184

### CODE REVIEW

**Review by jiangliu — APPROVED** [review]

**Comment by sameo** [comment]
Thanks @katexochen . I guess this PR will have to be modified with the new kbs-types release. Otherwise LGTM.

**Review by sameo — APPROVED** [review]

**Comment by katexochen** [comment]
@sameo I have that change prepared, but I'm still waiting for the crate to be published: https://crates.io/crates/kbs-types/versions

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
It seems that we have a unit test failure @katexochen

**Comment by katexochen** [comment]
@sameo The failing test isn't related to my change, right? This seems to be the failure mentioned in https://app.slack.com/client/T08PSQ7BQ/C050S70D9SR/thread/C050S70D9SR-1688691629.377139

**Comment by katexochen** [comment]
Could anyone rerun the failed test? @sameo @jiangliu @jialez0

**Comment by Xynnn007** [comment]
Hi @katexochen , could you please rebase the code? I think the error here has been fixed.

**Comment by arronwy** [comment]
The failure is not related to this PR, can we merged directly? @Xynnn007

**Pull request merged**
