### PR TITLE
image-rs: change namespace of ICR images

### PR DESCRIPTION
**Pull request by mattarnoatibm**
Change the namespace of images stored in ICR used
for the simple signing XRSS tests.

Fixes: confidential-containers#382

### CODE REVIEW

**Comment by mattarnoatibm** [comment]
@stevenhorsman would need to change the `SH_ICR_API_KEY` credential in github before this change could be merged into main.

**Comment by stevenhorsman** [comment]
> @stevenhorsman would need to change the `SH_ICR_API_KEY` credential in github before this change could be merged into main.

I've updated it now

**Review by stevenhorsman — APPROVED** [review]
I've testing this locally with the updated API key and the tests are working for me:
```
/image-rs# cargo test -p image-rs --no-default-features --features=kata-cc-native-tls,keywrap-jwe,signature-simple-xrss
...
running 2 tests
test signature_verification ... ok
test signature_verification_xrss ... ok
```

**Review by arronwy — APPROVED** [review]
Thanks @mattarnoatibm LGTM!

**Comment by Xynnn007** [comment]
PR to fix the lint error https://github.com/confidential-containers/guest-components/pull/390

**Review by Xynnn007 — APPROVED** [review]
LGTM

**Pull request merged**
