### PR TITLE
lint: fix lint error due to Rust 1.83.0 (stable) update

### PR DESCRIPTION
**Pull request by Xynnn007**

### CODE REVIEW

**Comment by mythi** [comment]
just a small nit on the commit message. our contrib guide suggests that code paths are prefixed with a subsystem name so this should probable be: `attestation-agent: fix xyz linter error`.

does this show up only with some specific features combination or why CI does not pick this up?

**Comment by Xynnn007** [comment]
Mostly because the rust toolchain updates. previous successful one https://github.com/confidential-containers/guest-components/actions/runs/12062059299/job/33635128074?pr=824#step:3:118
failed one https://github.com/confidential-containers/guest-components/actions/runs/12113386185/job/33768253307?pr=820#step:3:112

**Comment by mkulke** [comment]
> Mostly because the rust toolchain updates. previous successful one https://github.com/confidential-containers/guest-components/actions/runs/12062059299/job/33635128074?pr=824#step:3:118 failed one https://github.com/confidential-containers/guest-components/actions/runs/12113386185/job/33768253307?pr=820#step:3:112

I think Mikko was referring to the missing format checks on commit messages. I don't think the strings themselves are being checked, afaik it's just verified whether the commit msg has a "<something>: <some msg>" headline

**Comment by mythi** [comment]
I wasn't thinking about commit message CI checks. The comment about commit messages was just my manual review feedback and the question about CI checks was just that what triggers those changes. Looks like it's because `stable` now pointing to a new version...

**Review by mkulke — APPROVED** [review]

**Pull request merged**
