### PR TITLE
CDH/eHSM: add features for eHSM support

### PR DESCRIPTION
**Pull request by Xynnn007**
1. Both `Ehsm` and `ehsm` should be supported when a sealed secret indicates the kms type
2. added ehsm feature to confidential data hub binary build to leaverage the ability.

### CODE REVIEW

**Comment by Xynnn007** [comment]
cc @1570005763

**Review by 1570005763 — APPROVED** [review]
LGTM

**Review by fitzthum — APPROVED** [review]
LGTM (merge conflict)

**Comment by arronwy** [comment]
verified unseal secrets with eHSM, thanks a lot! @Xynnn007 @1570005763

**Pull request merged**
