### PR TITLE
CDH | Add Aliyun STS Token support for KMS

### PR DESCRIPTION
**Pull request by Xynnn007**
cc @1570005763

### CODE REVIEW

**Review by 1570005763 — COMMENTED** [review]
Nice work. Just curious, given that STS token is often a short-lived access credential, in what scenarios will 'sts_token_client' be used?

**Comment by Xynnn007** [comment]
Yes. This is used in some scenarios where aliyun KMS will only be used at the launch time. In this scene a short-term token is enough.

**Review by 1570005763 — CHANGES_REQUESTED** [review]
LGTM. Once all checks have been passed, it can be merged.

**Comment by Xynnn007** [comment]
@1570005763 Yea. Also a commit to make aliyun kms suites statically built-able.

**Review by 1570005763 — APPROVED** [review]
LGTM

**Review by jialez0 — APPROVED** [review]

**Pull request merged**
