### PR TITLE
Add Cargo.lock for consistent builds

### LINKED ISSUE #268: Missing Cargo.lock file
There is no Cargo.lock file commited in this repo, as it is listed in the .gitignore file. We should commit the lock file to prevent supply chain security issues.

### PR DESCRIPTION
**Pull request by beraldoleal**
Adding Cargo.lock ensures all workspace packages use the same dependency versions. This leads to consistent builds and resolves issues with missing lock files when using vendored source code.

Resolves errors like: "the source
git+https://github.com/sigstore/sigstore-rs.git?rev=69e8f33 requires a lock file to be present first before it can be used against vendored source code."

Fixes #268.

### CODE REVIEW

**Comment by beraldoleal** [comment]
Hi @jialez0 @Xynnn007, do you see any reason for keeping lock out this repo?

When doing builds from vendors we hit the issue described at the commit.

**Comment by Xynnn007** [comment]
> Hi @jialez0 @Xynnn007, do you see any reason for keeping lock out this repo?
> 
> When doing builds from vendors we hit the issue described at the commit.

First thanks for the contribution! It is really useful.

As @fitzthum said, we had added the Cargo.lock in the separate `attestation-agent` repo that is archive now. After merging repos the Cargo.lock file was lost.

**Review by Xynnn007 — APPROVED** [review]

**Comment by dcmiddle** [comment]
> Hi @jialez0 @Xynnn007, do you see any reason for keeping lock out this repo?
> 
> When doing builds from vendors we hit the issue described at the commit.

Can you describe this a little more? I don't think we hit this in the CoCo release process and I'd like to understand the vendor experience better.

**Comment by surajssd** [comment]
Not sure about the `sigstore-rs` dependency but I did hit this problem with clap's dependency `anstyle`. I have filed an issue about it here: https://github.com/confidential-containers/guest-components/issues/354

**Comment by surajssd** [comment]
Having a lock file may solve this problem.

**Review by surajssd — CHANGES_REQUESTED** [review]
@beraldoleal can you rebase on the latest commit from `main` and generate this file again?

**Review by sameo — APPROVED** [review]
Thanks for fixing that one @beraldoleal

**Comment by beraldoleal** [comment]
@surajssd done.

**Review by surajssd — APPROVED** [review]

**Comment by arronwy** [comment]
> @surajssd done.

The updated version of lock file seems upgrade `anstyle` to `1.0.3` which request (error: package `anstyle v1.0.3` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0):
```
[[package]]
name = "anstyle"
version = "1.0.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b84bf0a05bbb2a83e5eb6fa36bb6e87baa08193c35ff52bbf6b38d8af2890e46"
```

**Review by arronwy — APPROVED** [review]
I just notice CCv0 have upgraded rust toolchain to 1.72.0, this lock file works with this version

**Comment by arronwy** [comment]
https://github.com/kata-containers/kata-containers/pull/7918

**Pull request merged**
