### PR TITLE
Update base64 crate in guest-components

### PR DESCRIPTION
**Pull request by Xynnn007**
This PR mainly aims to:
1. update base64 version to v0.21.2
2. Make it clear that all the encodings used in image encryption/decryption are base64 with STANDARD alphabet. (While KBS Protocol's is with URL_SAFE_NO_PAD)

### CODE REVIEW

**Comment by Xynnn007** [comment]
Let's postpone this PR into v0.8.0 cycle. As it changes the base64 version and I am not sure if it will not break the current CI.

**Comment by mythi** [comment]
@Xynnn007 The Occlum attester test fixes are already in my PR #167. Perhaps we prioritize that?

**Comment by mythi** [comment]
> Let's postpone this PR into v0.8.0 cycle. As it changes the base64 version and I am not sure if it will not break the current CI.

This currently has "Drop: v0.7.0". Moving to v0.8.0 according to this.

**Review by arronwy — APPROVED** [review]
Thanks @Xynnn007  LGTM!

base64::encode in 0.13.0 is equivalent as  general_purpose::STANDARD in 0.21.2

**Pull request merged**
