### PR TITLE
Bump csv-rs for openssl 3 support

### PR DESCRIPTION
**Pull request by EmmEff**
Support building with openssl 3

### CODE REVIEW

**Review by Xynnn007 — APPROVED** [review]

**Comment by Xynnn007** [comment]
Thanks for this! @EmmEff let's see if the CI is happy

**Review by mythi — CHANGES_REQUESTED** [review]
I'd like to request a bump to `hyper-tls` (see #614) as part of this (manual) PR on dependencies.

**Review by fitzthum — APPROVED** [review]
LGTM. There are probably a few things we can bump as a result either in this PR or later. We should do this in Trustee too.

**Comment by fitzthum** [comment]
> I'd like to request a bump to hyper-tls (see https://github.com/confidential-containers/guest-components/pull/614) as part of this (manual) PR on dependencies.

@mythi Let's make a follow-up for this.

**Pull request merged**
